### 1. Get address
GET http://192.168.4.41:8090/restconf/data/tailf-ncs:devices/device=j0/address 
Authorization: Basic admin admin

### 2. Live-status
POST http://192.168.4.41:8090/restconf/operations/tailf-ncs:devices/device=xr-2/live-status/exec/show
Authorization: Basic admin admin
Content-Type: application/yang-data+xml

<show>
<args>ipv4 int brief</args>
</show>


### 3. Create services
PATCH http://192.168.4.41:8090/restconf/data/mybgp:mybgp?dry-run=native
Authorization: Basic admin admin
Content-Type: application/yang-data+xml

<mybgp xmlns="http://example.com/mybgp">
  <name>test</name>
  <dev1>xr-1</dev1>
  <dev2>xr-2</dev2>
  <asnum>100</asnum>
</mybgp>

